BEGIN;

CREATE TABLE IF NOT EXISTS searchs (
    id uuid NOT NULL PRIMARY KEY,
    search text NOT NULL,
    userId uuid NOT NULL,
    version integer NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT fk_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMIT;

